blueprint:
  name: Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            device_class: occupancy
            domain: binary_sensor
          multiple: true
    light_target:
      name: Light(s)
      selector:
        target:
          domain: light
    light_on_timeout:
      name: Light-on Timeout (minutes)
      description: Maximum time a light can stay on before it’s re-evaluated for shutdown.
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
          mode: slider

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

variables:
  light_entity_ids: >
    {{ expand(!input light_target) | map(attribute='entity_id') | list }}
    
triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
  # Self-healing timeout trigger
  - platform: state
    entity_id: !input light_entity_ids
    to: 'on'
    for:
#     minutes: !input light_on_timeout
      minutes: 5

actions:
  - action: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      - trigger: state
        entity_id: !input motion_entity
        from: "on"
        to: "off"
  - action: light.turn_off
    target: !input light_target
