blueprint:
  name: Open shutters if daylight (generic)
  description: >
    Opens shutters when selected lights are on for a set duration or when the light sensor detects daylight.
    Runs only if custom conditions are met (e.g., holiday/night mode off). After opening, turns off lights.
  domain: automation

  input:
    lights:
      name: Lights
      description: Lights that trigger the automation.
      selector:
        target:
          entity:
            domain: light

    light_sensor:
      name: Light Sensor
      description: Binary or numeric sensor indicating daylight or brightness.
      selector:
        entity:
          domain: 
            - binary_sensor
            - sensor

    shutter:
      name: Shutter
      description: Cover entity to open.
      selector:
        target:
          entity:
            domain: cover

    light_on_duration:
      name: Light On Duration
      description: How long the lights must stay on before triggering.
      default: "00:00:30"
      selector:
        text:

    daylight_duration:
      name: Daylight Duration
      description: How long daylight must be detected before triggering.
      default: "00:01:00"
      selector:
        text:

    extra_conditions:
      name: Extra Conditions (optional)
      description: >
        Add one or more extra conditions that must be true for the automation to run (e.g., holiday mode off).
      default: []
      selector:
        condition: {}

triggers:
  - alias: Light on
    trigger: state
    target: !input lights
    to: "on"
    for: !input light_on_duration
  - alias: Daylight detected
    trigger: state
    entity_id: !input light_sensor
    from: "off"
    to: "on"
    for: !input daylight_duration

conditions:
  - condition: and
    conditions: !input extra_conditions

actions:
  - alias: Open shutter
    action: cover.open_cover
    target: !input shutter
  - delay: "00:00:10"
  - alias: Turn off lights
    action: light.turn_off
    target: !input lights

mode: single
